---
plugin: aws_ec2
regions:
  - sa-east-1

hostnames:
  - private-ip-address

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: "_"

compose:
  ansible_host: private_ip_address

vars:
  ansible_user: ec2-user
  ansible_ssh_common_args: >
    -o ProxyCommand="ssh -i /var/lib/jenkins/.ssh/redis-ha-key
    -o StrictHostKeyChecking=no
    -W %h:%p ec2-user@56.125.164.56"
