---
plugin: amazon.aws.aws_ec2

regions:
  - sa-east-1

filters:
  tag:Project: "redis-ha-demo"

strict: False

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address

groups:
  master-redis: "'master' in tags.Role"
  replica-redis: "'replica' in tags.Role"
  bastion: "'bastion' in tags.Role"
