---
plugin: aws_ec2
regions:
  - "sa-east-1"
keyed_groups:
  - key: tags.Name
    prefix: ""
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address

# NEW JUMP HOST CONFIG
vars:
  ansible_ssh_common_args: "-o ProxyCommand='ssh -i /var/lib/jenkins/.ssh/redis-ha-key -W %h:%p ec2-user@56.125.164.56'"
